/**
 * Kundali Hook
 *
 * Fetches the persisted production Kundali generated by the
 * Swiss Ephemeris-backed Kundali pipeline.
 */

'use client'

import { useDataFetch } from './useDataFetch'
import { useUserStore } from '@/store/user-store'

export interface PersistedKundaliData {
  meta: {
    birthDetails?: unknown
    generatedAt?: string | null
    chartType?: string
    houseSystem?: string
    [key: string]: unknown
  }
  D1: {
    chartType?: string
    grahas?: Record<string, any>
    bhavas?: Record<string, any>
    lagna?: any
    aspects?: any[]
    [key: string]: unknown
  } | null
  dasha: any
}

export function useKundali() {
  const { user } = useUserStore()

  const { data, loading, error, refetch } =
    useDataFetch<PersistedKundaliData>({
      fetcher: async () => {
        const response = await fetch('/api/kundali/get', {
          credentials: 'include',
        })

        if (!response.ok) {
          const payload = await response.json().catch(() => ({}))
          throw new Error(
            payload?.error || 'Failed to load Kundali'
          )
        }

        const payload = await response.json()

        if (!payload?.kundali) {
          throw new Error('Kundali data missing from response')
        }

        return payload.kundali
      },
      dependencies: [user?.uid],
      enabled: !!user?.uid,
    })

  return {
    kundali: data,
    loading,
    error,
    refetch,
  }
}
